version: "3.8"

services:
  blockchain:
    image: node:18-alpine
    container_name: local-blockchain
    working_dir: /app
    volumes:
      - .:/app
    command: npx hardhat node
    ports:
      - "8545:8545"
    networks:
      - vault-net

  deployer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: vault-deployer
    depends_on:
      - blockchain
    working_dir: /app
    volumes:
      - .:/app
    command: sh ./docker/entrypoint.sh
    networks:
      - vault-net

networks:
  vault-net:
    driver: bridge
